(add-to-list 'load-path "~/.emacs.d/vendor")

(setq custom-file "~/.emacs.d/kal/custom.el")
(load custom-file 'noerror)

(load "kal/env")
(load "kal/global")
(load "kal/defuns")
(load "kal/bindings")
(load "kal/tabs")
(load "kal/disabled")
(load "kal/fonts")
(load "kal/utf-8")
(load "kal/scratch")
(load "kal/grep")
(load "kal/diff")
(load "kal/ido")
(load "kal/dired")
(load "kal/recentf")
(load "kal/rectangle")
(load "kal/org")
(load "kal/zoom")
(load "kal/flymake")
(load "kal/javascript")
(load "kal/ri-emacs")
(load "kal/mac")
(load "kal/server-mode")
(load "kal/shell-mode")
(load "kal/private" 'noerror)

;; (load "kal/hl-line")
;; (load "kal/iswitchb")

(vendor 'color-theme)
(vendor 'ruby-mode)
(vendor 'rinari)
(vendor 'textmate)
(vendor 'maxframe)
(vendor 'filladapt)
(vendor 'coffee-mode)
(vendor 'haml-mode)
(vendor 'sass-mode)
(vendor 'htmlize)
(vendor 'full-ack      'ack 'ack-same 'ack-find-same-file 'ack-find-file 'ack-interactive)
(vendor 'cdargs        'cv 'cdargs)
(vendor 'magit         'magit-status)
(vendor 'psvn          'svn-status)
(vendor 'js2-mode      'js2-mode)
(vendor 'markdown-mode 'markdown-mode)
(vendor 'textile-mode  'textile-mode)
(vendor 'csv-mode      'csv-mode)
(vendor 'yaml-mode     'yaml-mode)
(vendor 'inf-ruby      'inf-ruby)
(vendor 'rcodetools    'xmp)
(vendor 'yasnippet)
(vendor 'jekyll)
(vendor 'lua-mode      'lua-mode)
(vendor 'feature-mode)
(vendor 'mode-line-bell)
(vendor 'revbufs       'revbufs)

;; (vendor 'ruby-electric 'ruby-electric-mode)
;; (vendor 'auctex)
