# Generic Gemfile
source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'ember-rails', git: 'git://github.com/emberjs/ember-rails.git' # so we get the pre version
gem 'rack-mini-profiler', git: 'git://github.com/SamSaffron/MiniProfiler'
gem 'ruby-requirejs'

gem 'haml-rails', '~> 0.4'

gem 'sidekiq'
gem 'sinatra', require: nil
gem 'slim'  # required for sidekiq-web
gem 'therubyracer', require: 'v8'

# For use with external rest services (CapcoWebService, security service, ElasticSearch)
gem 'httparty'
gem 'httmultiparty'

# MongoDB
gem 'mongo', '1.6.2'
gem 'bson'
gem 'bson_ext'
gem 'mongoid', '2.4.12'
gem 'mongo_session_store-rails3'

gem 'pg'
gem 'activerecord-postgres-hstore'

# Elastic Search gems
gem 'elasticsearch'
gem 'tire', '0.4.3'
gem 'tire-contrib'

group :assets do
  gem 'compass'
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'coffee-script'  # need this to compile coffee on the fly
  gem 'uglifier'
end

# http://net.tutsplus.com/tutorials/html-css-techniques/sass-vs-less-vs-stylus-a-preprocessor-shootout/
gem 'stylus'  # https://github.com/lucasmazza/ruby-stylus
# http://learnboost.github.io/stylus/
# https://github.com/LearnBoost/stylus/blob/master/docs/firebug.md

# Deploy with Capistrano
gem 'capistrano', '2.14.1'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
#group :development, :test do
  gem 'guard-jasmine'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'jasminerice'
  gem 'pry-rails',  '~> 0.3.2'
  gem 'pry-nav',  '~> 0.2.3'
  gem 'pry-stack_explorer'
  gem 'better_errors',  '~> 1.0.1'
  gem 'binding_of_caller',  '~> 0.7.2'
  gem 'rails_best_practices',  '~> 1.14.4'
  gem 'sextant',  '~> 0.2.4'
  gem 'capybara',  '~> 1.1.2'
  gem 'rspec-rails',  '~> 2.14.0'
  gem 'spork',  '~> 0.9.2'
  gem 'launchy',  '~> 2.1.2'
#end

#group :test do
  gem 'simplecov', '~> 0.7.1', :require => false
#end

#platforms :ruby do
  gem 'puma',  '~> 2.6.0'
#end
